matrix:
  include:
    - os: linux
      env: NODE_VERSION=8
script:
  - test-ci.sh
before_install:
  - sudo add-apt-repository ppa:sauce/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install flvtool2 -y
addons:
  apt:
    packages:
    - wget
    - tar
    - bzip2
